
import { OptimizationResult } from '../types';

/**
 * Since we don't have direct access to the 'docx' library in this simulated environment 
 * without an import map, we'll implement a simple Blob-based download for text 
 * that mimics the behavior. In a real production React app, we would use:
 * import { Document, Packer, Paragraph, TextRun } from 'docx';
 */
export async function exportToDocx(result: OptimizationResult) {
  // Use the full optimized resume generated by the model
  const fullContent = result.fullOptimizedResume;

  // We create a Blob with the text content. 
  // In a production environment, this would be a proper .docx binary.
  const blob = new Blob([fullContent], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Revised_Resume_${Date.now()}.docx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
